# Generated by Django 2.0.4 on 2018-04-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.CharField(max_length=254)),
                ('user_answer', models.CharField(max_length=254)),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vote'),
        ),
    ]
