# Generated by Django 2.0.4 on 2018-04-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180408_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='type_font',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='type_show',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
